// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"homework/week4/internal/biz"
	"homework/week4/internal/data"
	"homework/week4/internal/service"
)

// Injectors from wire.go:

func InitService(sql string) service.Event {
	dao := data.NewDao(sql)
	greeter := biz.NewGreeter(dao)
	event := service.NewEvent(greeter)
	return event
}
